### ISSUE TITLE
error when running infer_trajectory with paga_tree method and umap embedding_type

### ISSUE THREAD

**Issue by lixin4306ren** [dynverse/ti_paga_tree#2]
It works for `embedding_type="fa"` but not `umap`. 

```
Error: Error during trajectory inference 
Traceback (most recent call last):
  File "/code/run.py", line 117, in <module>
    dimred = pd.DataFrame([x for x in adata.obsm['X_umap'].T]).T
  File "/usr/local/lib/python3.7/site-packages/numpy/core/records.py", line 506, in __getitem__
    obj = super(recarray, self).__getitem__(indx)
ValueError: no field of name X_umap

```

**Comment by zouter** [comment]
I have a hard time reproducing this, I'm running the following with the latest version of paga tree:

```
library(dyno)

dataset <- dyntoy::generate_dataset(num_cells = 1000, num_features = 100)
trajectory <- infer_trajectory(dataset, "dynverse/ti_paga_tree:v0.9.9.05", embedding_type = "umap", n_top_genes = 2000)
```

And it works. Could you try the same with `dynverse/ti_paga_tree:v0.9.9.05` @lixin4306ren ? This new version will be pushed to dynmethods soon once all methods finish building.

Thanks!

**Comment by zouter** [comment]
New version is now in dynverse/dynmethods master.

**Comment by rcannood** [comment]
@lixin4306ren Can you confirm whether reinstalling dynmethods fixes your problem?
